--- 
- www
- admin
- blog
- mail
- trac
- svn
- git
- mingle
- ci
- test
- preview
- staging
- nightly
- login
- logout
- register
- account
- accounts
- site
- sites
- artifact
- artifacts
- visitor
- visitors
- user
- users
- item
- items
- author
- authors
- category
- categories
- document_type
- document_types
- membership
- memberships
- news
- news_post
- news_posts
- browse
- about
- sitestyle
- featured
- featured_item
- featured_items
